{{- if $.Values.storageClass.enabled }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-stc
provisioner: "{{ $.Values.storageClass.provisioner }}"
parameters:
    type: {{ $.Values.storageClass.type }}
    fstype: {{ $.Values.storageClass.fstype }}
 {{- end }}


